# Generated by Django 5.2.5 on 2025-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.TimeField(auto_created=True),
        ),
    ]
